### ISSUE TITLE
Upon multiple languages, only the first is parsed and returned

### ISSUE THREAD

**Issue by phoenix-violeus** [mrcook/gutenberg_rdf#2]
A few ebooks, such as #17440, have multiple languages. However, rdf.rb only parses and returns the first. I believe that the fix is a simple matter of altering rdf.rb at lines 51-55 and then rdf at line 22 like so:

`
    def language
      languages = Array.new
      xml.elements.each('pgterms:ebook/dcterms:language') do |language|
        languages << language.elements['rdf:Description/rdf:value'].text
      end
      languages
    end
`

`
puts " Language: #{rdf.language.join('-')}"
`

**Comment by mrcook** [comment]
Hi PhoenixVioleus, thanks for the request. This sounds like a useful thing to add so I'll try to find some time to update code.

**Comment by mrcook** [comment]
@PhoenixVioleus I've now made the update (https://github.com/mrcook/gutenberg_rdf/commit/4834165f0b328027d9ac41aaf8a9bb0f2aaad602) and push a new gem. Thanks again!

**Comment by phoenix-violeus** [comment]
No problem! Thanks for the repo! It's been a great help to me
